#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/love_ice_orange_1.0?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #rabbitmq基本配置
  rabbitmq:
    addresses: 192.168.137.44:5672
    username: guest
    password: guest
    host: 192.168.137.44
    port: 5672
    virtual-host: /
    connection-timeout: 15000
  #rabbitmq消费端配置
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        acknowledge-mode: manual
        prefetch: 1

#端口,项目名
server:
  port: 8080
  servlet:
    context-path: /love_ice_orange

#mybatis mapper路径配置
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/*Mapper.xml

#mybatis mapper.xml配置路径
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
